# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: ProjectDefaultConfig
metadata:
  annotations:
    meta.upbound.io/example-id: identityplatform/v1beta1/projectdefaultconfig
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    signIn:
    - allowDuplicateEmails: true
      anonymous:
      - enabled: true
      email:
      - enabled: true
        passwordRequired: false
      phoneNumber:
      - enabled: true
        testPhoneNumbers:
          "+11231231234": "0000000"
