# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: networkmanagement.gcp.upbound.io/v1beta1
kind: ConnectivityTest
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanagement/v1beta1/connectivitytest
  labels:
    testing.upbound.io/example-name: instance-test
  name: instance-test
spec:
  forProvider:
    destination:
      - instanceSelector:
          matchLabels:
            testing.upbound.io/example-name: destination
    name: conn-test-instances
    protocol: TCP
    source:
      - instanceSelector:
          matchLabels:
            testing.upbound.io/example-name: source

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanagement/v1beta1/connectivitytest
  labels:
    testing.upbound.io/example-name: destination
  name: destination
spec:
  forProvider:
    zone: us-central1-a
    bootDisk:
      - initializeParams:
          - imageSelector:
              matchLabels:
                testing.upbound.io/example-name: image
    machineType: e2-medium
    networkInterface:
      - accessConfig:
          - {}
        networkSelector:
          matchLabels:
            testing.upbound.io/example-name: vpc

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanagement/v1beta1/connectivitytest
  labels:
    testing.upbound.io/example-name: source
  name: source
spec:
  forProvider:
    zone: us-central1-a
    bootDisk:
      - initializeParams:
          - imageSelector:
              matchLabels:
                testing.upbound.io/example-name: image
    machineType: e2-medium
    networkInterface:
      - accessConfig:
          - {}
        networkSelector:
          matchLabels:
            testing.upbound.io/example-name: vpc

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanagement/v1beta1/connectivitytest
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider: {}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanagement/v1beta1/connectivitytest
  labels:
    testing.upbound.io/example-name: image
  name: image
spec:
  forProvider:
    rawDisk:
      - source: https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-97.98-google-kvm-ubuntu-xenial-go_agent-raw-1557960142.tar.gz
