# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: gke.gcp.upbound.io/v1beta2
kind: BackupBackupPlan
metadata:
  annotations:
    uptest.upbound.io/disable-import: "true"
    meta.upbound.io/example-id: gke/v1beta2/backupbackupplan
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    backupConfig:
      allNamespaces: true
      includeSecrets: true
      includeVolumeData: true
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    location: us-central1

---

apiVersion: container.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: gke/v1beta2/backupbackupplan
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    deletionProtection: false
    addonsConfig:
      gkeBackupAgentConfig:
        enabled: true
    initialNodeCount: 1
    location: us-central1
    removeDefaultNodePool: false
