# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/image
  labels:
    testing.upbound.io/example-name: image
  name: image
spec:
  forProvider:
    rawDisk:
      - source: https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-97.98-google-kvm-ubuntu-xenial-go_agent-raw-1557960142.tar.gz
